# Generated by Django 3.2.21 on 2024-08-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategory',
            new_name='Category',
        ),
    ]
