# Generated by Django 3.2.21 on 2024-08-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='preview',
            field=models.ImageField(blank=True, upload_to='services/preview/'),
        ),
    ]
